export const ADD_RULE = 'ADD_RULE'
export const ADD_CHILD_RULE_RELATION = 'ADD_CHILD_RULE_RELATION'
export const UPDATE_RULE_VALUE = 'UPDATE_RULE_VALUE'
export const UPDATE_ACTIVE_RULESET = 'UPDATE_ACTIVE_RULESET'
